version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: micro-erp-php
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      bash -c "apt-get update && 
      apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip curl && 
      docker-php-ext-configure gd --with-freetype --with-jpeg && 
      docker-php-ext-install gd mysqli pdo pdo_mysql &&
      a2enmod rewrite &&
      apache2-foreground"

  db:
    image: mysql:5.7
    container_name: micro-erp-mysql
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      MYSQL_DATABASE: micro_erp
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql

volumes:
  mysql_data: